"""
humanizer.py — Two-pass Gemini rewriter (aggressive humanization edition).

WHY TWO PASSES:
  Pass 1 — Destroys AI structure completely.
            Changes syntax at skeleton level: passive→active, cleft sentences,
            fronted adverbials, nominalization reversal, question embedding.
            Forces unpredictable sentence length rhythm (burstiness).

  Pass 2 — Makes it sound like a real expert human wrote it.
            Adds reasoning connectives, hedges, mild imperfections.
            Deliberately removes the "too polished" quality detectors flag.

WHY THIS BEATS DETECTORS:
  AI detectors measure two core signals:
    1. PERPLEXITY  — how surprising each word choice is
                     AI always picks the statistically safest word → low perplexity
                     We fix this by forcing rare constructions and unexpected vocab

    2. BURSTINESS  — how much sentence length varies
                     AI writes uniform medium sentences → low burstiness
                     We fix this by enforcing explicit rhythm patterns like:
                     [long, short, long, medium, short]
                     A 3-word sentence after a 40-word sentence spikes burstiness

TARGET: < 15% AI detection score AND < 15% plagiarism score
"""

import re
import time
import random
from typing import Optional

from google import genai
from google.genai import types


# ── Burstiness rhythm patterns ────────────────────────────────────────────────
# Each pattern is injected into the Gemini prompt to control sentence rhythm.
# Variety across retries ensures different structural outcomes.
BURSTINESS_PATTERNS = [
    "very long (30+ words), very short (3-5 words), long (20-25 words), medium (12-15 words), short (5-8 words)",
    "medium (15 words), short (4 words), very long (35+ words), short (6 words), long (22 words), medium (13 words)",
    "long (25 words), short (3 words), medium (14 words), very long (30+ words), short (5 words)",
    "short (4 words), very long (40+ words), medium (12 words), short (6 words), long (20 words)",
]

# ── Rare syntactic structures to inject ──────────────────────────────────────
# These constructions are essentially never generated by AI naturally.
# Injecting them spikes perplexity scores dramatically.
RARE_STRUCTURES = [
    "Use an absolute phrase (e.g., 'The analysis complete, researchers then turned to...')",
    "Use an inverted sentence for emphasis (e.g., 'Rarely has a technology moved so fast.')",
    "Use a mid-sentence parenthetical aside with dashes — like this one — for effect",
    "Use a rhetorical question embedded mid-paragraph (e.g., 'But why does this matter?')",
    "Use a tricolon (three parallel items) with deliberately unequal lengths",
    "Start one sentence with a present participle (e.g., 'Drawing on decades of research...')",
    "Use an appositive phrase to define a term mid-sentence",
]

# ── Vocabulary replacement bank ───────────────────────────────────────────────
# Forces substitution of ultra-common AI words with rarer equivalents.
# These replacements appear in the prompt as explicit instructions.
VOCAB_REPLACEMENTS = """
MANDATORY vocabulary substitutions (replace these exact words):
- "significant" → "pronounced" or "marked" or "considerable"
- "important" → "consequential" or "telling" or leave implicit
- "however" → "yet" or "even so" or "still" or "then again"
- "therefore" → "hence" or "and so" or "this is why"
- "additionally" → "on top of that" or "what's more" or "beyond this"
- "implement" → "put in place" or "roll out" or "execute"
- "utilize" → "use" or "draw on" or "apply"
- "demonstrate" → "show" or "reveal" or "make clear"
- "facilitate" → "help" or "allow" or "make possible"
- "indicate" → "suggest" or "point to" or "hint at"
- "regarding" → "on" or "about" or "when it comes to"
- "numerous" → "many" or "a string of" or "no shortage of"
- "various" → "a range of" or "different" or "assorted"
"""


def _char_window(n: int, tol: float = 0.07) -> tuple[int, int]:
    """Return ±7% character count window around n."""
    d = int(n * tol)
    return (n - d, n + d)


def _pick_rare_structure(attempt: int) -> str:
    """Pick a rare syntactic structure, cycling through options on retries."""
    return RARE_STRUCTURES[attempt % len(RARE_STRUCTURES)]


def _build_pass1_prompt(text: str, char_count: int, attempt: int) -> str:
    """
    Pass 1: Structural destruction and reconstruction.

    Goal: Make the text unrecognisable at the syntactic level
    while preserving 100% of the factual content.

    The prompt gets more aggressive on each retry attempt.
    """
    min_c, max_c = _char_window(char_count)
    rhythm       = BURSTINESS_PATTERNS[attempt % len(BURSTINESS_PATTERNS)]
    rare         = _pick_rare_structure(attempt)

    aggression = ""
    if attempt == 1:
        aggression = "\n⚠ PREVIOUS ATTEMPT FAILED AI DETECTION. Be more unconventional. Use more unexpected sentence structures."
    elif attempt >= 2:
        aggression = "\n🚨 CRITICAL: TWO PREVIOUS ATTEMPTS FAILED. This text MUST read as unmistakably human. Use the most unusual grammatical constructions you can while keeping meaning intact. No safe choices."

    return f"""You are an expert academic editor. Your job is to completely reconstruct the syntactic skeleton of the paragraph below so it reads as authentic human writing — not AI output.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
ABSOLUTE RULES (violations = task failure):
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
1. Output ONLY the rewritten paragraph. No preamble, no labels, no quotes.
2. Output length MUST be {min_c}–{max_c} characters. Count carefully.
3. Every fact, statistic, technical term, and proper noun must be preserved exactly.
4. Do NOT add new information. Do NOT remove existing information.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
STRUCTURAL TRANSFORMATION RULES (apply ALL):
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
1. SENTENCE RHYTHM — Use this exact length pattern: {rhythm}
   This is the single most important rule. Uniform sentence length = detected as AI.

2. SYNTAX INVERSION — Transform at least 3 of these:
   - Passive voice → active voice
   - Noun phrases → verb-led constructions ("the implementation of X" → "implementing X")
   - Subject-verb-object → fronted adverbial + subject ("In practice, researchers found...")
   - Coordinate clauses → subordinate clauses or vice versa

3. RARE STRUCTURE — Include this exact construction: {rare}

4. OPENING — Do NOT start with "The", "This", "In", "It", "AI", or "Artificial".
   Use an unexpected opener: a participle, an adverb, a short punchy claim.

5. VOCABULARY — {VOCAB_REPLACEMENTS}

6. REGISTER — Academic but not sterile. Write like a sharp human expert,
   not like a formal report generator.{aggression}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
INPUT PARAGRAPH:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
{text}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
REWRITTEN PARAGRAPH (output ONLY this, nothing else):
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"""


def _build_pass2_prompt(text: str, attempt: int) -> str:
    """
    Pass 2: Human fingerprinting.

    Takes the structurally rewritten text from Pass 1 and adds
    the subtle markers that distinguish expert human writing:
    - Reasoning connectives that show thinking process
    - Mild epistemic hedges
    - One deliberate imperfection for rhythm
    - Removal of any remaining AI-typical smoothness

    CRITICAL: This pass must NOT re-introduce AI patterns.
    """
    hedge = random.choice([
        "arguably", "in most cases", "to some extent",
        "at least in part", "more often than not", "broadly speaking"
    ])
    connective = random.choice([
        "That said,", "Even so,", "The trouble is,",
        "What this means, in practice, is that",
        "Worth noting here is that", "Curiously,",
        "Then again,", "To be fair,", "Admittedly,",
        "The reason for this is straightforward:",
    ])

    return f"""You are polishing academic writing to sound unmistakably human — warm, expert, and slightly imperfect in the way that real scholars write.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
ABSOLUTE RULES:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
1. Output ONLY the final paragraph. No labels, no commentary, no quotes.
2. Preserve ALL facts and technical content exactly.
3. Stay within ±10% of the input character count.
4. Do NOT make it sound casual or unprofessional.
5. NEVER introduce word-merging — every word must be properly space-separated.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
HUMANIZATION RULES (apply 3-4 of these):
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
1. Insert this exact connective naturally into the text: "{connective}"
   Place it at a sentence boundary where it fits the reasoning flow.

2. Add the hedge word "{hedge}" once, where it genuinely applies.

3. It is acceptable — even encouraged — to begin ONE sentence with "And" or "But".
   This is standard in expert academic prose and spikes human-likeness scores.

4. One sentence may be a deliberate fragment for rhythmic effect.
   Example: "A difficult trade-off, certainly." after a long complex sentence.

5. Replace any remaining smooth transitions ("Furthermore,", "Additionally,",
   "Moreover,") with more specific reasoning language:
   "This matters because...", "The implication is...", "Part of the reason is..."

6. If any sentence still reads like a template, rewrite its opening word only.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
INPUT:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
{text}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
FINAL HUMANIZED PARAGRAPH (output ONLY this):
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"""


class GeminiHumanizer:
    """
    Two-pass Gemini rewriter.
    Uses gemini-2.0-flash — fast (~3s/call) and cost-efficient.
    With parallel processing: a 60-page doc finishes in ~2 minutes.
    """

    def __init__(self, api_key: str, model_name: str = "gemini-2.0-flash"):
        self.client     = genai.Client(api_key=api_key)
        self.model_name = model_name
        self.config     = types.GenerateContentConfig(
            temperature=0.95,    # High temperature = more unpredictable = lower perplexity scores
            top_p=0.97,
            top_k=50,
            max_output_tokens=2048,
        )

    def _call(self, prompt: str, retries: int = 3) -> Optional[str]:
        """
        Call Gemini with exponential backoff on rate-limit errors.
        Strips any accidental markdown formatting from the response.
        """
        for i in range(retries):
            try:
                resp = self.client.models.generate_content(
                    model=self.model_name,
                    contents=prompt,
                    config=self.config,
                )
                if resp.text:
                    # Strip markdown fences the model occasionally adds
                    clean = re.sub(r"^```[a-z]*\n?|```$", "", resp.text, flags=re.MULTILINE).strip()
                    # Strip any label prefixes the model might add
                    clean = re.sub(r"^(REWRITTEN PARAGRAPH|HUMANIZED PARAGRAPH|OUTPUT):?\s*", "", clean, flags=re.IGNORECASE).strip()
                    return clean
                return None
            except Exception as e:
                err = str(e).lower()
                if any(x in err for x in ["quota", "rate", "429", "limit"]):
                    wait = (2 ** i) * 5
                    time.sleep(wait)
                else:
                    raise
        return None

    def rewrite_structural(self, text: str, original_char_count: int, attempt: int = 0) -> Optional[str]:
        """
        Pass 1: Destroy and rebuild sentence structure.
        More aggressive on each retry attempt.
        """
        return self._call(_build_pass1_prompt(text, original_char_count, attempt))

    def rewrite_conversational(self, text: str, attempt: int = 0) -> Optional[str]:
        """
        Pass 2: Add human fingerprints.
        Uses randomised connectives and hedges for variety.
        """
        return self._call(_build_pass2_prompt(text, attempt))