#!/usr/bin/env python3
"""
humanize_doc.py — Humanize a .docx via humanizeai.pro

Usage:
    python3 humanize_doc.py input.docx output.docx
    python3 humanize_doc.py input.docx output.docx --concurrency 5
    python3 humanize_doc.py input.docx output.docx --dry-run
    python3 humanize_doc.py input.docx output.docx --visible
    python3 humanize_doc.py input.docx output.docx --visible --concurrency 1   # debug single tab

Requires:
    pip install patchright python-docx
    python3 -m patchright install chromium
"""

import argparse
import asyncio
import copy
import re
import sys
import time
from pathlib import Path

from docx import Document
from docx.oxml import OxmlElement
from docx.oxml.ns import qn

try:
    from patchright.async_api import async_playwright, TimeoutError as PWTimeout
    BROWSER_LIB = "patchright"
except ImportError:
    from playwright.async_api import async_playwright, TimeoutError as PWTimeout
    BROWSER_LIB = "playwright (install patchright to bypass Cloudflare)"


# ─── CONFIG ──────────────────────────────────────────────────────────────────

SITE_URL = "https://www.humanizeai.pro/"

SKIP_STYLE_KEYWORDS = [
    'heading', 'title', 'caption', 'toc ', 'table of', 'code',
    'figure', 'list bullet', 'list number', 'footnote', 'header', 'footer',
    'bibliography', 'index',
]
MIN_WORDS = 15   # paragraphs shorter than this are skipped

# Hard boilerplate markers — everything from first match onward is discarded
BOILERPLATE_MARKERS = [
    "Yes, the content generated by our tool is crafted to bypass",
    "Q12: Does the tool maintain",
    "We use cookies to ensure that we give you the best experience",
    "© 2026 humanizeai.pro",
    "Response in 3-5 business days",
    "AI Humanizer For College",
    "reCAPTCHA and the Google",
    "A2: The tool uses advanced algorithms",
    "A3: Yes, our AI Humanizer is completely free",
    "Content Creators & Writers: Streamline",
    "Marketing Professionals & Ad Experts:",
    "Students: Ideal for assignments",
    "Feature Request & Issue Report",
    "All rights reserved",
    "Boosting Conversions through Emotional Engagement",
    "Enhancing Search Engine Compatibility",
    "Building Trust with Credibility and Feedback",
    "Anyone with a Story to Tell:",
    "Necessity of Humanizing AI Text",
    "Creating Relatable and Authentic Content",
    "Emotionally charged content strengthens business",
    "Start using our AI Humanizer",
    "We bypass ALL detectors",
    "Introducing Humanize AI:",
    "Humanize AI stands out as",
]

LINE_NOISE_RE = [
    re.compile(r"^\d+\s+words?\s*$", re.I),
    re.compile(r"^Free\s+Standard\s+Academic", re.I),
    re.compile(r"^Ultra\s+run$", re.I),
    re.compile(r"^Expand\s+More$", re.I),
    re.compile(r"^Humanize\s+AI\s*$", re.I),
    re.compile(r"^Check\s+for\s+AI", re.I),
    re.compile(r"^Expected\s+time", re.I),
    re.compile(r"added\s+change\s*$", re.I),
]

# Rotate user-agents across workers
USER_AGENTS = [
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:125.0) Gecko/20100101 Firefox/125.0",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 14_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.4.1 Safari/605.1.15",
    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
]

PAGE_LOAD_TIMEOUT = 60_000
OUTPUT_POLL_SECS  = 120
CHUNK_WORDS       = 175
CONCURRENCY       = 5


# ─── DOCX HELPERS ────────────────────────────────────────────────────────────

def should_skip(para):
    txt = para.text.strip()
    if not txt:
        return True
    if para._element.findall('.//' + qn('w:drawing')):
        return True
    if (para._element.findall('.//' + qn('m:oMath')) or
            para._element.findall('.//' + qn('m:oMathPara'))):
        return True
    style = para.style.name.lower()
    if any(kw in style for kw in SKIP_STYLE_KEYWORDS):
        return True
    words = txt.split()
    if len(words) < MIN_WORDS:
        return True
    if not any(c in txt for c in ['.', ',']):
        return True
    if txt.count('…') > 2 or txt.count('.....') > 2:
        return True
    if re.match(r'^\[\d+\]', txt):
        return True
    return False


def extract_paragraphs(doc):
    return [(idx, para, para.text.strip())
            for idx, para in enumerate(doc.paragraphs)
            if not should_skip(para)]


def chunk_paragraphs(para_list, max_words):
    chunks, current, current_words = [], [], 0
    for item in para_list:
        wc = len(item[2].split())
        if wc > max_words:
            if current:
                chunks.append(current); current, current_words = [], 0
            chunks.append([item])
        elif current_words + wc > max_words:
            chunks.append(current)
            current, current_words = [item], wc
        else:
            current.append(item); current_words += wc
    if current:
        chunks.append(current)
    return chunks


def replace_paragraph_text(para, new_text):
    runs = para.runs
    if not runs:
        new_r = OxmlElement('w:r')
        new_t = OxmlElement('w:t')
        new_t.text = new_text
        new_t.set('{http://www.w3.org/XML/1998/namespace}space', 'preserve')
        new_r.append(new_t)
        para._element.append(new_r)
        return
    runs[0].text = new_text
    for run in runs[1:]:
        run.text = ""


# ─── OUTPUT CLEANING ─────────────────────────────────────────────────────────

def clean_output(raw: str, original: str) -> str:
    """Remove site boilerplate and UI chrome from extracted text."""
    # Cut at first hard boilerplate marker
    cut = len(raw)
    for marker in BOILERPLATE_MARKERS:
        idx = raw.lower().find(marker.lower())
        if 0 <= idx < cut:
            cut = idx
    raw = raw[:cut]

    # Strip line-level noise
    lines = raw.split('\n')
    cleaned = []
    for line in lines:
        ls = line.strip()
        if not ls:
            continue
        if any(rx.search(ls) for rx in LINE_NOISE_RE):
            continue
        cleaned.append(ls)

    result = '\n\n'.join(cleaned).strip()

    # Sanity: result must be at least 30% as long as original
    if not result or len(result.split()) < len(original.split()) * 0.3:
        return ""
    return result


# ─── JAVASCRIPT: extract only the output (right) panel ───────────────────────
#
# The site layout:  [ INPUT (left) | OUTPUT (right) ]
# The output panel contains <a> hyperlinks with colored text.
# We find it by:
#   1. Looking for a div in the RIGHT half of the viewport
#   2. That contains multiple <a> tags (the colored word links)
#   3. Whose innerText does NOT start with our input text
# If that fails we fall back to finding the two largest text blocks
# and returning the rightmost one.

JS_GET_OUTPUT = """
(inputText) => {
    const inputFirst50 = inputText.trim().slice(0, 50).toLowerCase();

    // Helper: is this element in the right half of the page?
    function isRightSide(el) {
        const r = el.getBoundingClientRect();
        return r.left > window.innerWidth * 0.3 && r.width > 100 && r.height > 50;
    }

    // Helper: count <a> links inside an element
    function linkCount(el) {
        return el.querySelectorAll('a').length;
    }

    // Helper: is the innerText clearly different from the input?
    function isOutput(el) {
        const txt = (el.innerText || '').trim();
        return txt.length > 80 && !txt.toLowerCase().startsWith(inputFirst50);
    }

    // Strategy 1: right-side div with 3+ links that isn't the input
    const allDivs = Array.from(document.querySelectorAll('div, section, article, p'));
    const candidates = allDivs.filter(el =>
        isRightSide(el) && linkCount(el) >= 3 && isOutput(el)
    );

    if (candidates.length > 0) {
        // Sort by link count desc, then by area asc (most specific)
        candidates.sort((a, b) => {
            const diff = linkCount(b) - linkCount(a);
            if (diff !== 0) return diff;
            const aA = a.getBoundingClientRect().width * a.getBoundingClientRect().height;
            const bA = b.getBoundingClientRect().width * b.getBoundingClientRect().height;
            return aA - bA;
        });
        return candidates[0].innerText.trim();
    }

    // Strategy 2: find two big text blocks sorted by horizontal position,
    // return the rightmost one
    const blocks = allDivs.filter(el => {
        const txt = (el.innerText || '').trim();
        const r = el.getBoundingClientRect();
        return txt.length > 150 && r.width > 200 && r.height > 80;
    }).sort((a, b) =>
        b.getBoundingClientRect().left - a.getBoundingClientRect().left
    );

    for (const el of blocks) {
        const txt = (el.innerText || '').trim();
        if (!txt.toLowerCase().startsWith(inputFirst50)) {
            return txt;
        }
    }

    return '';
}
"""


# ─── BROWSER HELPERS ─────────────────────────────────────────────────────────

async def find_input(page):
    for sel in ["textarea.chakra-textarea", "textarea", "[contenteditable='true']"]:
        try:
            await page.wait_for_selector(sel, timeout=6000)
            return sel
        except Exception:
            continue
    return None


async def click_humanize(page):
    for label in ["Humanize", "humanize", "HUMANIZE"]:
        try:
            btn = page.get_by_role("button", name=label)
            if await btn.count() > 0:
                await btn.first.click(timeout=10_000)
                return True
        except Exception:
            pass
    try:
        await page.click("button:has-text('Humanize')", timeout=10_000)
        return True
    except Exception:
        pass
    try:
        for btn in await page.query_selector_all("button"):
            if "humanize" in (await btn.inner_text()).lower():
                await btn.click(timeout=10_000)
                return True
    except Exception:
        pass
    return False


async def wait_for_result(page):
    """Wait for 'Expected time' to appear then disappear."""
    deadline = time.time() + OUTPUT_POLL_SECS
    timer_seen = False

    while time.time() < deadline:
        try:
            body = await page.inner_text("body")
            if "Expected time" in body:
                timer_seen = True
                await asyncio.sleep(2)
                continue
            elif timer_seen:
                await asyncio.sleep(2)   # one extra beat after timer clears
                return
        except Exception:
            pass
        await asyncio.sleep(1.5)

    # Timer never appeared or never cleared — wait a flat extra 8s
    if not timer_seen:
        await asyncio.sleep(8)


async def get_output(page, chunk_text: str, chunk_id: int, probe: bool) -> str:
    """Extract the output panel text using JS, fall back to body-text split."""
    # Try JS right-panel extraction first
    try:
        raw = await page.evaluate(JS_GET_OUTPUT, chunk_text)
    except Exception as e:
        raw = ""
        if probe:
            print(f"    [chunk {chunk_id:03d}] JS eval error: {e}")

    if probe:
        print(f"\n  ── PROBE chunk {chunk_id:03d} ──")
        print(f"  JS returned ({len(raw)} chars): {raw[:400]}")

    if raw and len(raw.strip()) > 50:
        result = clean_output(raw, chunk_text)
        if result:
            return result

    # Fallback: body text split on input anchor
    if probe:
        print(f"  JS empty → falling back to body split")
    try:
        body = await page.inner_text("body")
    except Exception:
        return ""

    orig = chunk_text.strip()
    if orig in body:
        after = body.split(orig, 1)[-1]
    else:
        anchor = " ".join(orig.split()[:25])
        after = body.split(anchor, 1)[-1] if anchor in body else body[len(body)//2:]

    return clean_output(after, chunk_text)


# ─── SINGLE CHUNK ────────────────────────────────────────────────────────────

async def process_chunk(ctx, chunk_text: str, chunk_id: int, probe: bool) -> str:
    page = await ctx.new_page()
    try:
        print(f"  [chunk {chunk_id:03d}] Loading...")
        await page.goto(SITE_URL, wait_until="domcontentloaded", timeout=PAGE_LOAD_TIMEOUT)
        await asyncio.sleep(3)

        inp = await find_input(page)
        if not inp:
            await page.screenshot(path=f"/tmp/chunk_{chunk_id}_no_input.png")
            raise Exception("No textarea found")

        await page.fill(inp, chunk_text)
        print(f"  [chunk {chunk_id:03d}] {len(chunk_text.split())}w → Humanize...")
        await asyncio.sleep(0.8)

        if not await click_humanize(page):
            await page.screenshot(path=f"/tmp/chunk_{chunk_id}_no_btn.png")
            raise Exception("Humanize button not found")

        await wait_for_result(page)

        result = await get_output(page, chunk_text, chunk_id, probe)

        if not result or result.strip() == chunk_text.strip():
            await page.screenshot(path=f"/tmp/chunk_{chunk_id}_fail.png")
            print(f"  [chunk {chunk_id:03d}] ⚠  No output → keeping original")
            print(f"                    screenshot: /tmp/chunk_{chunk_id}_fail.png")
            return chunk_text

        print(f"  [chunk {chunk_id:03d}] ✓  {len(result.split())}w")
        return result

    except PWTimeout as e:
        print(f"  [chunk {chunk_id:03d}] TIMEOUT: {str(e).splitlines()[0]}")
        return chunk_text
    except Exception as e:
        print(f"  [chunk {chunk_id:03d}] ERROR: {e}")
        return chunk_text
    finally:
        await page.close()


# ─── WORKER ──────────────────────────────────────────────────────────────────

async def worker(browser, queue, results, probe, worker_id):
    """
    Each worker owns one browser context and drains chunks from the shared queue.
    Context is closed HERE before the event loop can be torn down.
    (Fixes 'BrowserContext.close: no running event loop' crash)
    """
    ctx = await browser.new_context(
        user_agent=USER_AGENTS[worker_id % len(USER_AGENTS)],
        viewport={"width": 1280 + worker_id * 11, "height": 900},
        locale="en-US",
        timezone_id="America/New_York",
    )
    await asyncio.sleep(worker_id * 1.5)   # stagger startup
    try:
        while True:
            try:
                chunk_id, chunk_text = queue.get_nowait()
            except asyncio.QueueEmpty:
                break
            results[chunk_id] = await process_chunk(ctx, chunk_text, chunk_id, probe)
            queue.task_done()
    except Exception as e:
        print(f"  [worker {worker_id}] fatal: {e}")
    finally:
        # Close context inside the still-running event loop — avoids the crash
        try:
            await ctx.close()
        except Exception:
            pass   # already closed or loop teardown — safe to ignore


# ─── ORCHESTRATOR ────────────────────────────────────────────────────────────

async def run_all(chunks_text, concurrency, headless, probe):
    async with async_playwright() as p:
        browser = await p.chromium.launch(
            headless=headless,
            args=["--no-sandbox", "--disable-dev-shm-usage"],
        )
        try:
            queue = asyncio.Queue()
            for i, txt in enumerate(chunks_text):
                await queue.put((i, txt))

            results = [None] * len(chunks_text)
            n = min(concurrency, len(chunks_text))
            print(f"  Spawning {n} isolated browser contexts...\n")

            # gather() keeps the event loop alive until ALL workers finish,
            # so ctx.close() inside each worker's finally block always has a loop
            await asyncio.gather(*[
                worker(browser, queue, results, probe, wid)
                for wid in range(n)
            ])
        finally:
            await browser.close()

    return results


# ─── DOCUMENT RECONSTRUCTION ─────────────────────────────────────────────────

def reconstruct_doc(doc, chunks, results, chunk_texts):
    for chunk, humanized, orig_text in zip(chunks, results, chunk_texts):
        if not humanized or humanized.strip() == orig_text.strip():
            continue
        n  = len(chunk)
        hp = [p.strip() for p in humanized.split("\n\n") if p.strip()]
        if not hp:
            continue
        if len(hp) == n:
            pairs = list(zip(chunk, hp))
        elif len(hp) > n:
            pairs = list(zip(chunk, hp[:n-1]))
            pairs.append((chunk[-1], " ".join(hp[n-1:])))
        else:
            pairs = [(chunk[i], hp[i] if i < len(hp) else hp[-1]) for i in range(n)]
        for (_, para, orig), new_text in pairs:
            if new_text and new_text.strip() != orig.strip():
                replace_paragraph_text(para, new_text)


# ─── MAIN ────────────────────────────────────────────────────────────────────

def main():
    ap = argparse.ArgumentParser(
        description="Humanize a .docx via humanizeai.pro",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python3 humanize_doc.py report.docx out.docx                        normal run
  python3 humanize_doc.py report.docx out.docx --concurrency 5        5 parallel tabs
  python3 humanize_doc.py report.docx out.docx --dry-run              preview chunks
  python3 humanize_doc.py report.docx out.docx --visible --concurrency 1   debug mode
        """)
    ap.add_argument("input")
    ap.add_argument("output")
    ap.add_argument("--concurrency", type=int, default=CONCURRENCY)
    ap.add_argument("--chunk-words", type=int, default=CHUNK_WORDS)
    ap.add_argument("--dry-run",  action="store_true")
    ap.add_argument("--visible",  action="store_true", help="Show browser window")
    ap.add_argument("--probe",    action="store_true", help="Print raw JS extraction output")
    args = ap.parse_args()

    src = Path(args.input)
    if not src.exists():
        sys.exit(f"ERROR: {src} not found.")

    print(f"\n{'='*55}")
    print(f"  Browser     : {BROWSER_LIB}")
    print(f"  Input       : {src}")
    print(f"  Output      : {args.output}")
    print(f"  Workers     : {args.concurrency}")
    print(f"  Chunk limit : {args.chunk_words} words")
    print(f"{'='*55}\n")

    doc = Document(str(src))
    para_list = extract_paragraphs(doc)
    total = sum(1 for p in doc.paragraphs if p.text.strip())
    print(f"Paragraphs : {total} total | {total-len(para_list)} skipped | {len(para_list)} to humanize")

    chunks = chunk_paragraphs(para_list, args.chunk_words)
    words  = sum(len(p[2].split()) for p in para_list)
    eta    = int((len(chunks) / args.concurrency) * 18)
    m, s   = divmod(eta, 60)
    print(f"Chunks     : {len(chunks)}  ({words} words)  ~{m}m {s}s estimated\n")

    chunk_texts = ["\n\n".join(p[2] for p in ch) for ch in chunks]

    if args.dry_run:
        for i, ct in enumerate(chunk_texts):
            print(f"[Chunk {i:03d}] {len(ct.split())}w | {len(chunks[i])} para(s)")
            print(ct[:200] + ("..." if len(ct)>200 else ""))
            print("-"*50)
        return

    t0 = time.time()
    results = asyncio.run(run_all(
        chunk_texts, args.concurrency,
        headless=not args.visible, probe=args.probe
    ))
    elapsed = time.time() - t0

    changed = sum(1 for o, r in zip(chunk_texts, results)
                  if r and r.strip() != o.strip())
    print(f"\n  {changed}/{len(chunks)} chunks humanized in {elapsed:.0f}s")
    print("  Rebuilding document...")
    reconstruct_doc(doc, chunks, results, chunk_texts)
    doc.save(args.output)
    m2, s2 = divmod(int(elapsed), 60)
    print(f"\n✓  Saved → {args.output}  ({m2}m {s2}s)\n")


if __name__ == "__main__":
    main()